version: '3'

services:
  db:
    image: postgres:latest
    volumes:
      - postgresDb:/var/lib/postgresql/data
    restart: always
    env_file:
      - .env

  web:
    build: .
    command: python manage.py migrate && python manage.py runserver 0.0.0.0:8800
    volumes:
      - .:/app
    ports:
      - 8800:8800
    depends_on:
      - db

volumes:
  postgresDb:
