# Generated by Django 4.0.1 on 2022-01-09 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('data', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='First_parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_value', models.FloatField(unique=True, verbose_name='Значение')),
                ('date_for_the_first', models.DateField(verbose_name='Дата')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
            ],
        ),
        migrations.CreateModel(
            name='Second_parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('y_value', models.FloatField(unique=True, verbose_name='Значение')),
                ('date_for_the_second', models.DateField(verbose_name='Дата')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='имя')),
                ('password', models.CharField(max_length=50, verbose_name='Пароль')),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_data_type', models.CharField(max_length=50, verbose_name='Вид данных_x')),
                ('y_data_type', models.CharField(max_length=50, verbose_name='Вид данных_y')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user', verbose_name='Пользователь')),
                ('x_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.first_parameter', verbose_name='Значение для x')),
                ('y_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.second_parameter', verbose_name='Значение для y')),
            ],
        ),
        migrations.CreateModel(
            name='Correlation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_data_type', models.CharField(max_length=50, verbose_name='Вид данных_x')),
                ('y_data_type', models.CharField(max_length=50, verbose_name='Вид данных_y')),
                ('value', models.FloatField(verbose_name='коэффициент корреляции')),
                ('p_value', models.FloatField(verbose_name='двухстороннее p-значение')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user', verbose_name='Пользователь')),
            ],
            options={
                'ordering': ['user_id'],
            },
        ),
    ]
