# Generated by Django 4.0.1 on 2022-01-13 08:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correlation',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='data',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='first_parameter',
            name='x_value',
            field=models.FloatField(verbose_name='Значение'),
        ),
        migrations.AlterField(
            model_name='second_parameter',
            name='y_value',
            field=models.FloatField(verbose_name='Значение'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
