# Generated by Django 4.0.1 on 2022-01-13 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_alter_correlation_user_id_alter_data_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correlation',
            name='p_value',
            field=models.FloatField(verbose_name='двухстороннее п-значение'),
        ),
        migrations.AlterField(
            model_name='correlation',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.RemoveField(
            model_name='data',
            name='x_value',
        ),
        migrations.AddField(
            model_name='data',
            name='x_value',
            field=models.ManyToManyField(to='main.First_parameter', verbose_name='Значения для x'),
        ),
        migrations.RemoveField(
            model_name='data',
            name='y_value',
        ),
        migrations.AddField(
            model_name='data',
            name='y_value',
            field=models.ManyToManyField(to='main.Second_parameter', verbose_name='Значения для y'),
        ),
    ]
