# Generated by Django 4.0.1 on 2022-01-16 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_correlation_p_value_alter_correlation_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='created_at',
            field=models.DateField(verbose_name='Дата создания'),
        ),
    ]
