# Generated by Django 4.0.1 on 2022-01-17 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_data_x_value_data_x_value_remove_data_y_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='x_value',
        ),
        migrations.AddField(
            model_name='data',
            name='x_value',
            field=models.ManyToManyField(to='main.First_parameter', verbose_name='Значения для x'),
        ),
        migrations.RemoveField(
            model_name='data',
            name='y_value',
        ),
        migrations.AddField(
            model_name='data',
            name='y_value',
            field=models.ManyToManyField(to='main.Second_parameter', verbose_name='Значения для y'),
        ),
    ]
