# Generated by Django 4.0.1 on 2022-01-17 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_data_x_value_data_x_value_remove_data_y_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='x_value',
        ),
        migrations.AddField(
            model_name='data',
            name='x_value',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.first_parameter', verbose_name='Значения для x'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='data',
            name='y_value',
        ),
        migrations.AddField(
            model_name='data',
            name='y_value',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.second_parameter', verbose_name='Значения для y'),
            preserve_default=False,
        ),
    ]
